// @flow

/**
 * Flowtype definitions for CommandInstruction
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

declare export var INSERT_TEXT_AT_CURSOR: any; // "INSERT_TEXT_AT_CURSOR"

declare export var SELECT_RANGE: any; // "SELECT_RANGE"

export interface InsertTextAtCursorInstruction {
  type: typeof INSERT_TEXT_AT_CURSOR;
  text: string;
}

export interface SelectRangeInstruction {
  type: typeof SELECT_RANGE;
  selectionStart: number;
  selectionEnd: number;
}

export type Instruction =
  | InsertTextAtCursorInstruction
  | SelectRangeInstruction;
