// @flow

/**
 * Flowtype definitions for FunctionTypes
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import * as React from 'react';

export type GenerateMarkdownPreview = (markdown: string) => Promise<React.Node>;

/**
 * If the command returns true for a given KeyboardEvent,
 * the command is executed
 */
export type HandleKeyCommand = (
  e: React.KeyboardEvent<HTMLTextAreaElement>
) => boolean;
