// @flow

/**
 * Flowtype definitions for L18n
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import * as React from 'react';

export interface L18n {
  write: React.Node;
  preview: React.Node;
  uploadingImage: string;
  pasteDropSelect: string;
}
