// @flow

/**
 * Flowtype definitions for MarkdownState
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import { Selection } from "./Selection";

export interface MarkdownState {
  selection: Selection;
  text: string;
}
