// @flow
/**
 * Flowtype definitions for refs
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import * as React from 'react';

export type RefObj<ElementType> = { current: null | ElementType };

export interface Refs {
  textarea?: RefObj<HTMLTextAreaElement>;
  preview?: RefObj<HTMLDivElement>;
}
