// @flow

/**
 * Flowtype definitions for Suggestion
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import * as React from "react";

export interface Suggestion {
  /**
   * React element to be used as the preview
   */
  preview: React.Node;

  /**
   * Value that is going to be used in the text in case this suggestion is selected
   */
  value: string;
}
