// @flow

/**
 * Flowtype definitions for TextSection
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import { Selection } from "./Selection";

export interface TextSection {
  text: string;
  selection: Selection;
}
